#pragma once

#define HV_DEVICE_LINK       "\\\\.\\hv_device"
#define HV_DEVICE_NAME_W     L"\\Device\\hv_device"
#define HV_SYMBOLIC_NAME_W   L"\\DosDevices\\hv_device"

#define HV_IOCTL_BASE 0x800

// lol...
#define IOCTL_HV_NOP         CTL_CODE(FILE_DEVICE_UNKNOWN, HV_IOCTL_BASE + 0, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HV_QUERY_CAPS  CTL_CODE(FILE_DEVICE_UNKNOWN, HV_IOCTL_BASE + 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HV_START       CTL_CODE(FILE_DEVICE_UNKNOWN, HV_IOCTL_BASE + 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HV_STOP        CTL_CODE(FILE_DEVICE_UNKNOWN, HV_IOCTL_BASE + 3, METHOD_BUFFERED, FILE_ANY_ACCESS)